version: 2
updates:
  - package-ecosystem: "composer"
    directory: "/"
    schedule:
      interval: "daily"
      time: "01:00"
      timezone: "Asia/Taipei"
    versioning-strategy: increase-if-necessary
    allow:
      - dependency-type: "all"
    commit-message:
      prefix: "Mitake"
      include: "scope"
