os: linux
language: php

php:
- 7.4
- nightly

jobs:
  allow_failures:
  - php: nightly

cache:
  directories:
  - $HOME/.composer/cache/files
  - vendor

install:
- composer install --prefer-dist

script:
- composer run cs-check
- composer run coverage

after_success:
- bash <(curl -s https://codecov.io/bash)
